import { DocPage } from './types'

export const faqPage: DocPage = {
  slug: 'faq',
  title: 'FAQ',
  description:
    'Frequently asked questions about Inference Intelligence.',

  sections: [
    {
      id: 'does-it-store-prompts',
      heading: 'Does Inference Intelligence store my prompts or AI outputs?',
      body:
        'No. Inference Intelligence only reads cost and usage metadata from your ' +
        'AI provider APIs. We never see, store, or transmit your actual prompts, ' +
        'completions, images, or any other content generated by or sent to AI models.',
    },
    {
      id: 'which-providers',
      heading: 'Which AI providers are supported?',
      body:
        'We currently support OpenAI, Anthropic, Google Gemini, Azure OpenAI, ' +
        'AWS Bedrock, Groq, Mistral, and Cohere. ' +
        'Replicate and Hugging Face are coming in Q1 2025. ' +
        'See the Connecting Providers page for full details.',
    },
    {
      id: 'free-tier',
      heading: 'What is included in the free tier?',
      list: [
        'Up to 3 AI provider connections',
        'Up to 5 team members',
        'Last 30 days of cost history',
        'Basic dashboard and cost breakdown',
        'Email alerts only',
        'CSV export',
      ],
    },
    {
      id: 'data-retention',
      heading: 'How long is data retained?',
      table: {
        headers: ['Plan', 'Cost History', 'Alert History', 'Exports'],
        rows: [
          ['Free',         '30 days',    '7 days',   'Last 10 exports'    ],
          ['Starter',      '90 days',    '30 days',  'Last 50 exports'    ],
          ['Professional', '12 months',  '90 days',  'Unlimited'          ],
          ['Business',     '24 months',  '12 months','Unlimited'          ],
          ['Enterprise',   'Custom',     'Custom',   'Custom'             ],
        ],
      },
    },
    {
      id: 'cancel',
      heading: 'Can I cancel anytime?',
      body:
        'Yes. Monthly plans can be cancelled at any time with no penalty. ' +
        'Your access continues until the end of the current billing period. ' +
        'Annual plans are non-refundable after 14 days but can be downgraded.',
    },
    {
      id: 'change-plan',
      heading: 'Can I upgrade or downgrade my plan?',
      body:
        'Yes. Upgrades take effect immediately and are prorated. ' +
        'Downgrades take effect at the start of the next billing period. ' +
        'You will not lose historical data when downgrading.',
    },
    {
      id: 'sso',
      heading: 'Do you support Single Sign-On (SSO)?',
      body:
        'SSO via SAML 2.0 and OIDC is available on Team and Enterprise plans. ' +
        'We support Okta, Azure AD, Google Workspace, and any SAML-compliant provider. ' +
        'Contact support to enable SSO for your workspace.',
    },
    {
      id: 'api-key-security',
      heading: 'How are my API keys stored?',
      body:
        'API keys are encrypted with AES-256 before being written to our database. ' +
        'The plaintext key is never logged and never transmitted beyond the initial ' +
        'connection test. After saving, you cannot retrieve the full key — ' +
        'only the last 4 characters are shown for identification.',
    },
    {
      id: 'support',
      heading: 'How do I contact support?',
      body:
        'Free and Starter plan: email support@inferenceintelligence.com ' +
        '(response within 2 business days).\n\n' +
        'Professional plan: email with priority routing (response within 8 hours).\n\n' +
        'Business and Enterprise: dedicated Slack channel with your team ' +
        '(response within 1 hour during business hours).',
    },
  ],

  prev: { label: 'Troubleshooting', path: '/docs/troubleshooting' },
  next: undefined,
}