/**
 * OpenRouter Writer
 *
 * Handles all file I/O. Uses a write-to-temp-then-rename (atomic swap) pattern
 * so that existing output files are NEVER overwritten by a failed sync.
 *
 * Output files:
 *   data/models.json      - Machine-readable normalized model list
 *   data/models.md        - Human-readable organized model document
 *   data/sync-meta.json   - Lightweight sync metadata
 *
 * PRICING DISPLAY in Markdown:
 *   The API gives USD per token. We display USD per 1M tokens in Markdown
 *   by multiplying by 1,000,000. This is clearly labeled.
 */

import { readFile, writeFile, rename, unlink, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = path.resolve(__dirname, '..', '..', 'data');

const MODELS_JSON_PATH = path.join(DATA_DIR, 'models.json');
const MODELS_MD_PATH = path.join(DATA_DIR, 'models.md');
const SYNC_META_PATH = path.join(DATA_DIR, 'sync-meta.json');

/**
 * Ensures the data directory exists.
 */
async function ensureDataDir() {
  await mkdir(DATA_DIR, { recursive: true });
}

/**
 * Atomically writes content to a file using a temporary file.
 * If writing fails, the original file is untouched.
 *
 * @param {string} finalPath
 * @param {string} content
 */
async function atomicWrite(finalPath, content) {
  const tmpPath = finalPath + '.tmp';
  try {
    await writeFile(tmpPath, content, 'utf8');
    await rename(tmpPath, finalPath);
  } catch (err) {
    // Clean up the temp file if it exists
    try {
      await unlink(tmpPath);
    } catch {
      // Ignore cleanup errors
    }
    throw err;
  }
}

/**
 * Loads the currently saved models from disk.
 * Returns empty array if the file does not exist or cannot be parsed.
 *
 * @returns {Promise<object[]>}
 */
export async function loadExistingModels() {
  if (!existsSync(MODELS_JSON_PATH)) return [];
  try {
    const text = await readFile(MODELS_JSON_PATH, 'utf8');
    const parsed = JSON.parse(text);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

/**
 * Writes normalized models to data/models.json (atomically).
 *
 * @param {object[]} models
 */
export async function writeModelsJson(models) {
  await ensureDataDir();
  const content = JSON.stringify(models, null, 2);
  await atomicWrite(MODELS_JSON_PATH, content);
}

/**
 * Formats a price for Markdown display.
 * Converts from USD/token to USD/1M tokens.
 * Shows "Free" for 0, "N/A" for null.
 *
 * @param {number|null} pricePerToken
 * @returns {string}
 */
function formatPrice(pricePerToken) {
  if (pricePerToken === null || pricePerToken === undefined) return 'N/A';
  if (pricePerToken === 0) return 'Free';
  const per1m = pricePerToken * 1_000_000;
  return `$${per1m.toFixed(4)} / 1M tokens`;
}

/**
 * Formats context length for human readability.
 * @param {number|null} n
 * @returns {string}
 */
function formatContextLength(n) {
  if (n === null || n === undefined) return 'N/A';
  return n.toLocaleString('en-US') + ' tokens';
}

/**
 * Formats a boolean/null capability for display.
 * @param {boolean|null} val
 * @returns {string}
 */
function formatCapability(val) {
  if (val === true) return 'Yes';
  if (val === false) return 'No';
  return 'Unknown';
}

/**
 * Generates the human-readable Markdown document.
 *
 * @param {object[]} models
 * @param {string} syncTimestamp
 * @returns {string}
 */
function generateMarkdown(models, syncTimestamp) {
  const lines = [];

  lines.push('# OpenRouter Models');
  lines.push('');
  lines.push(`> Auto-generated by \`npm run sync:models\`. Do not edit manually.`);
  lines.push(`> Pricing unit: USD per 1M tokens (source: USD per token from OpenRouter API × 1,000,000).`);
  lines.push('');
  lines.push(`**Last Global Sync:** ${syncTimestamp}`);
  lines.push('');
  lines.push(`**Total Models:** ${models.length}`);
  lines.push('');
  lines.push('---');

  models.forEach((m, index) => {
    const p = m.pricing;
    const c = m.capabilities;

    lines.push('');
    lines.push(`## Model ${index + 1}`);
    lines.push('');
    lines.push('### Provider');
    lines.push(m.provider);
    lines.push('');
    lines.push('### Name');
    lines.push(m.name);
    lines.push('');
    lines.push('### Model ID');
    lines.push(`\`${m.model_id}\``);
    lines.push('');
    lines.push('### Context Length');
    lines.push(formatContextLength(m.context_length));
    lines.push('');
    lines.push('### Pricing');
    lines.push('');
    lines.push('| Type | Price |');
    lines.push('|---|---:|');
    lines.push(`| Input | ${formatPrice(p.input)} |`);
    lines.push(`| Output | ${formatPrice(p.output)} |`);
    lines.push(`| Cache Read | ${formatPrice(p.cache_read)} |`);
    lines.push(`| Cache Write | ${formatPrice(p.cache_write)} |`);
    lines.push('');
    lines.push('### Capabilities');
    lines.push('');
    lines.push('| Capability | Supported |');
    lines.push('|---|---|');
    lines.push(`| Text | ${formatCapability(c.text)} |`);
    lines.push(`| Image | ${formatCapability(c.image)} |`);
    lines.push(`| Audio | ${formatCapability(c.audio)} |`);
    lines.push(`| Video | ${formatCapability(c.video)} |`);
    lines.push(`| Tools | ${formatCapability(c.tools)} |`);
    lines.push(`| Reasoning | ${formatCapability(c.reasoning)} |`);
    lines.push('');
    lines.push('### Last Sync');
    lines.push(m.last_sync);
    lines.push('');
    lines.push('---');
  });

  return lines.join('\n');
}

/**
 * Writes human-readable Markdown to data/models.md (atomically).
 *
 * @param {object[]} models
 * @param {string} syncTimestamp
 */
export async function writeModelsMarkdown(models, syncTimestamp) {
  await ensureDataDir();
  const content = generateMarkdown(models, syncTimestamp);
  await atomicWrite(MODELS_MD_PATH, content);
}

/**
 * Writes sync metadata to data/sync-meta.json (atomically).
 *
 * @param {number} modelCount
 * @param {string} syncTimestamp
 */
export async function writeSyncMeta(modelCount, syncTimestamp) {
  await ensureDataDir();
  const meta = {
    source: 'https://openrouter.ai/api/v1/models',
    last_sync: syncTimestamp,
    model_count: modelCount,
    successful: true,
  };
  await atomicWrite(SYNC_META_PATH, JSON.stringify(meta, null, 2));
}
